input {
  file {
    path => "/data/movies.csv"
    start_position => "beginning"
    sincedb_path => "/dev/null"
    mode => "read"
  }
}

filter {
  csv {
    separator => ","
    skip_header => true
    columns => [
      "id",
      "title",
      "genres",
      "original_language",
      "overview",
      "popularity",
      "production_companies",
      "release_date",
      "budget",
      "revenue",
      "runtime",
      "status",
      "tagline",
      "vote_average",
      "vote_count",
      "credits",
      "keywords",
      "poster_path",
      "backdrop_path",
      "recommendations"
    ]
    }

  if ![title] or [title] == "" {
    drop { }
  }

  mutate {
    convert => {
      "id" => "integer"
      "popularity" => "float"
      "budget" => "float"
      "revenue" => "float"
      "runtime" => "float"
      "vote_average" => "float"
      "vote_count" => "integer"
    }
  }

  date {
    match => ["release_date", "yyyy-MM-dd"]
    target => "release_date"
  }

  mutate {
    remove_field => ["message", "event", "host", "log", "@version"]
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "movies_clean"
    document_id => "%{id}"
  }
  stdout { codec => rubydebug }
}
